In [9]:
import gym
import numpy as np
import random

# Initialize the FrozenLake environment
env = gym.make("FrozenLake-v1", is_slippery=False)

# Q-learning parameters
alpha = 0.1  # Learning rate
gamma = 0.99  # Discount factor
epsilon = 1.0  # Exploration rate
epsilon_min = 0.1  # Minimum exploration rate
epsilon_decay = 0.995  # Decay rate for exploration probability

# Initialize the Q-table
q_table = np.zeros((env.observation_space.n, env.action_space.n))

# Training parameters
num_episodes = 1000
max_steps_per_episode = 100

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    step = 0
    total_reward = 0
    
    while not done and step < max_steps_per_episode:
        # Exploration-exploitation tradeoff
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Explore
        else:
            action = np.argmax(q_table[state, :])  # Exploit
        
        # Take the action and observe the outcome
        next_state, reward, done, _ = env.step(action)
        
        # Update the Q-table
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state, :])
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value
        
        state = next_state
        step += 1
        total_reward += reward
    
    # Decay the exploration rate
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay
    
    if (episode + 1) % 100 == 0:
        print(f'Episode {episode + 1}/{num_episodes} - Total reward: {total_reward} - Epsilon: {epsilon}')
        print(f'Q-table snapshot:\n{q_table}')

# Evaluate the agent
num_eval_episodes = 100
total_rewards = 0

for episode in range(num_eval_episodes):
    state = env.reset()
    done = False
    step = 0
    episode_reward = 0
    
    while not done and step < max_steps_per_episode:
        action = np.argmax(q_table[state, :])  # Always exploit during evaluation
        next_state, reward, done, _ = env.step(action)
        episode_reward += reward
        state = next_state
        step += 1
    
    total_rewards += episode_reward

average_reward = total_rewards / num_eval_episodes
print(f'Average reward over {num_eval_episodes} evaluation episodes: {average_reward}')
env.close()


ValueError: too many values to unpack (expected 4)

In [15]:
import gym
import numpy as np
import random

# Initialize the FrozenLake environment
env = gym.make("FrozenLake-v1", is_slippery=False)

# Q-learning parameters
alpha = 0.1  # Learning rate
gamma = 0.99  # Discount factor
epsilon = 1.0  # Exploration rate
epsilon_min = 0.1  # Minimum exploration rate
epsilon_decay = 0.995  # Decay rate for exploration probability

# Initialize the Q-table
q_table = np.zeros((env.observation_space.n, env.action_space.n))

# Training parameters
num_episodes = 1000
max_steps_per_episode = 100

# Q-learning algorithm
for episode in range(num_episodes):
    state, _ = env.reset()
    done = False
    step = 0
    total_reward = 0
    
    while not done and step < max_steps_per_episode:
        # Exploration-exploitation tradeoff
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Explore
        else:
            action = np.argmax(q_table[state, :])  # Exploit
        
        # Take the action and observe the outcome
        next_state, reward, done, _, _ = env.step(action)
        
        # Update the Q-table
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state, :])
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value
        
        state = next_state
        step += 1
        total_reward += reward
    
    # Decay the exploration rate
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay
    
    if (episode + 1) % 100 == 0:
        print(f'Episode {episode + 1}/{num_episodes} - Total reward: {total_reward} - Epsilon: {epsilon}')
        print(f'Q-table snapshot:\n{q_table}')

# Evaluate the agent
num_eval_episodes = 100
total_rewards = 0

for episode in range(num_eval_episodes):
    state, _ = env.reset()
    done = False
    step = 0
    episode_reward = 0
    
    while not done and step < max_steps_per_episode:
        action = np.argmax(q_table[state, :])  # Always exploit during evaluation
        next_state, reward, done, _, _ = env.step(action)
        episode_reward += reward
        state = next_state
        step += 1
    
    total_rewards += episode_reward

average_reward = total_rewards / num_eval_episodes
print(f'Average reward over {num_eval_episodes} evaluation episodes: {average_reward}')
env.close()


Episode 100/1000 - Total reward: 0.0 - Epsilon: 0.6057704364907278
Q-table snapshot:
[[0.04469563 0.00701536 0.12116922 0.0305683 ]
 [0.02865372 0.         0.17258677 0.0458448 ]
 [0.049254   0.25238289 0.00491024 0.05288889]
 [0.0262485  0.         0.00165992 0.00183374]
 [0.00146484 0.01527574 0.         0.01114193]
 [0.         0.         0.         0.        ]
 [0.         0.37045823 0.         0.03299632]
 [0.         0.         0.         0.        ]
 [0.01043621 0.         0.04516631 0.00244931]
 [0.00354226 0.04720468 0.24777416 0.        ]
 [0.05699904 0.5853707  0.         0.0379258 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.07736966 0.24885276 0.03880836]
 [0.06782875 0.10442009 0.79410887 0.17136179]
 [0.         0.         0.         0.        ]]
Episode 200/1000 - Total reward: 1.0 - Epsilon: 0.3669578217261671
Q-table snapshot:
[[0.3480726  0.1367478  0.81596519 0.31273649]
 [0.31777836 0.         0.8578